-- Migration: Add check_in_code column to events table
-- Date: 2025-10-15
-- Purpose: Store 5-letter random codes for approved events

-- Add check_in_code column to events table
ALTER TABLE events 
ADD COLUMN IF NOT EXISTS check_in_code VARCHAR(5);

-- Add comment for documentation
COMMENT ON COLUMN events.check_in_code IS 'Five-letter random code generated when event is approved for attendance tracking';

-- Create index for faster lookups (optional but recommended)
CREATE INDEX IF NOT EXISTS idx_events_check_in_code ON events(check_in_code);

-- Note: The column is nullable since existing events won't have codes
-- New approved events will get codes generated by the application